CandyStore/UI/ViewModels/CandiesListViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UI.ViewModels
{
    public class CandiesListViewModel
    {
        public IEnumerable<Candy> Candies { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

CandyStore/UI/ViewModels/CartIndexViewModel.cs
using Domain.Entities;

namespace UI.ViewModels
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

CandyStore/UI/ViewModels/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UI.ViewModels
{
    public class PagingInfo
    {
        // Кол-во товаров
        public int TotalItems { get; set; }

        // Кол-во товаров на одной странице
        public int ItemsPerPage { get; set; }

        // Номер текущей страницы
        public int CurrentPage { get; set; }

        // Общее кол-во страниц
        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

CandyStore/UI/Controllers/AdminController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Controllers
{
    public class AdminController : Controller
    {
        ICandyRepository repository;

        public AdminController(ICandyRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index()
        {
            return View(repository.Candies);
        }
        public ViewResult Edit(int CandyId)
        {
            Candy candy = repository.Candies
                .FirstOrDefault(g => g.CandyId == CandyId);
            return View(candy);
        }
        public ViewResult Create()
        {
            return View("Edit", new Candy());
        }
        [HttpPost]
        public ActionResult Edit(Candy candy, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    candy.ImageMimeType = image.ContentType;
                    candy.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(candy.ImageData, 0, image.ContentLength);
                }
                repository.SaveChanges(candy);
                TempData["message"] = string.Format("Changes for \"{0}\" were saved", candy.Name);
                return RedirectToAction("Index");
            }
            else
            {
                // Что-то не так со значениями данных
                return View(candy);
            }
        }
        [HttpPost]
        public ActionResult Remove(int candyId)
        {
            Candy removeCandy = repository.Remove(candyId);
            if (removeCandy != null)
            {
                TempData["message"] = string.Format("Candy \"{0}\" was removed",
                    removeCandy.Name);
            }
            return RedirectToAction("Index");
        }
    }
}

CandyStore/UI/Controllers/CandyController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UI.ViewModels;

namespace UI.Controllers
{
    public class CandyController : Controller
    {
        // GET: Candy
        private ICandyRepository repository;
        public int pageSize = 4;
        public CandyController(ICandyRepository rep)
        {
            repository = rep;
        }
        public ViewResult List(string category, int page = 1)
        {
            CandiesListViewModel model = new CandiesListViewModel
            {
                Candies = repository.Candies
                .Where(candy => category == null || candy.Category == category)
                .OrderBy(candy => candy.CandyId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),

                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                    repository.Candies.Count() :
                    repository.Candies.Where(candy => candy.Category == category).Count(),
                },
                CurrentCategory = category,
            };
            return View(model);
        }
        public FileContentResult GetImage(int candyId)
        {
            Candy candy = repository.Candies
                .FirstOrDefault(c => c.CandyId == candyId);

            if (candy != null)
            {
                return File(candy.ImageData, candy.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

CandyStore/UI/Controllers/CartController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UI.ViewModels;

namespace UI.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        private ICandyRepository repository;
        public CartController(ICandyRepository repo)
        {
            repository = repo;
        }
        public ViewResult Index(Cart cart,string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int candyId, string returnUrl)
        {
            Candy candy = repository.Candies
                .FirstOrDefault(c => c.CandyId == candyId);

            if (candy != null)
            {
                cart.AddItem(candy, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int candyId, string returnUrl)
        {
            Candy candy = repository.Candies
                .FirstOrDefault(c => c.CandyId == candyId);

            if (candy != null)
            {
                cart.RemoveLine(candy);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
        public ViewResult Checkout(Cart cart, string returnUrl)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Dear user your cart is empty!");
                return View(new CartIndexViewModel
                {
                    Cart = cart,
                    ReturnUrl = returnUrl
                });
            }
            else
            {
                return View(new ShippingInfo());
            }
        }


        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingInfo shippingInfo)
        {

            if (ModelState.IsValid)
            {
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingInfo);
            }
        }
    }
}

CandyStore/UI/Controllers/NavCategoryController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UI.ViewModels;

namespace UI.Controllers
{
    public class NavCategoryController : Controller
    {
        private ICandyRepository repository;
        public NavCategoryController(ICandyRepository rep)
        {
            repository = rep;
        }
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Candies
                .Select(candy => candy.Category)
                .Distinct()
                .OrderBy(candy => candy);

            return PartialView(categories);
        }
    }
}

CandyStore/UI/Views/Admin/Edit.cshtml
@model Domain.Entities.Candy

@{
    ViewBag.Title = "Admin panel: Editing";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h3>Editing page</h3>
    </div>

    @using (Html.BeginForm("Edit", "Admin",
        FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="card-body">
            @Html.HiddenFor(m => m.CandyId)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "CandyId":
                    case "ImageData":
                    case "ImageMimeType":
                        
                        break;
                    default:
                        <div class="form-group">
                            <label>@(property.DisplayName ?? property.PropertyName)</label>
                            @if (property.PropertyName == "Description")
                            {
                                @Html.TextArea(property.PropertyName, null,
                                    new { @class = "form-control", rows = 5 })
                            }
                            else
                            {
                                @Html.TextBox(property.PropertyName, null,
                                    new { @class = "form-control" })
                            }
                            @Html.ValidationMessage(property.PropertyName)
                        </div>
                        break;
                }
            }
            <div class="card-group">
                <div class="input-group mb-3">
                    <input type="file" class="form-control" id="inputGroupFile01" name="Image">
                </div>
                @if (Model.ImageData == null)
                {
                    <div class="form-control-file">No image</div>
                }
                else
                {
                    <img class="img-thumbnail" width="150" height="150"
                         src="@Url.Action("GetImage", "Candy",
                        new { Model.CandyId })" />
                }
            </div>
        </div>
        <div class="card-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel changes", "Index", null, new
            {
                @class = "btn btn-default"
            })
        </div>
    }
</div>

CandyStore/UI/Views/Admin/Index.cshtml
@model IEnumerable<Domain.Entities.Candy>

@{
    ViewBag.Title = "Admin panel: candies list";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="card">
    <div class="card-header" style="margin: 20px;">
        <h3>List of candies</h3>
    </div>
    <div class="card-body border-0">
        <table class="table table-striped table-bordered table-hover">
            <tr>
                <th class="text-right">ID</th>
                <th class="text-right">Name</th>
                <th class="text-right">Price</th>
                <th class="text-right">Weight</th>
                <th class="text-center">Actions</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">@item.CandyId</td>
                    <td>@Html.ActionLink(item.Name, "Edit", new { item.CandyId })</td>
                    <td class="text-right">@item.Price RUB</td>
                    <td class="text-right">@item.Weight</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Remove", "Admin"))
                        {
                            @Html.Hidden("CandyId", item.CandyId)
                            <input type="submit"
                                   class="btn btn-danger"
                                   value="Delete" />
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="card-footer" style="margin: 0 auto">
        @Html.ActionLink("Add the candy", "Create", null,
            new { @class = "btn btn-sm btn-primary" })
    </div>
</div>

CandyStore/UI/Views/Candy/List.cshtml
@using UI.ViewModels
@using UI.HtmlUoW
@model CandiesListViewModel

@{
    ViewBag.Title = "Store";
}

@foreach (var candy in @Model.Candies)
{
    @Html.Partial("CandySummary", candy);
}

<div class="btn-group-lg float-sm-left">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", 
        new { page = x, category = Model.CurrentCategory }))
</div>

CandyStore/UI/Views/Cart/Checkout.cshtml
@model Domain.Entities.ShippingInfo

@{
    ViewBag.Title = "Checkout";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary();

    <h2>Shipping information</h2>
    <div class="form-group">
        <label>Name:</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Surname:</label>
        @Html.TextBoxFor(x => x.Surname, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Country:</label>
        @Html.TextBoxFor(x => x.Country, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>City:</label>
        @Html.TextBoxFor(x => x.City, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>First address:</label>
        @Html.TextBoxFor(x => x.AddressLine1, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Second address:</label>
        @Html.TextBoxFor(x => x.AddressLine2, new { @class = "form-control" })
    </div>

    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Apply" />
    </div>
}

CandyStore/UI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Confirmed";
}

<h2>Thank you!</h2>
<p>Thanks for your order. We do apprecite this deal</p>

CandyStore/UI/Views/Cart/Index.cshtml
@model UI.ViewModels.CartIndexViewModel

@{
    ViewBag.Title = "Shopping cart";
}

<h2>Your cart</h2>
<table class="table">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>Candy</th>
            <th class="text-right">Cost</th>
            <th class="text-right">Total cost</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Candy.Name</td>
                <td class="text-right">@line.Candy.Price RUB</td>
                <td class="text-right">
                    @((line.Quantity * line.Candy.Price)) RUB
                </td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("CandyId", line.Candy.CandyId)
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="btn btn-sm btn-danger" type="submit" value="Удалить" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue() RUB
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue your shopping</a>
    @Html.ActionLink("Checkout", "Checkout", null, new { @class = "btn btn-primary" })
</div>

CandyStore/UI/Views/Cart/Summary.cshtml
@model Domain.Entities.Cart

<div class="navbar-right nav-item active">
    @Html.ActionLink("Order", "Index", "Cart",
    new { returnUrl = Request.Url.PathAndQuery },
    new { @class = "btn btn-default" })
</div>

<div class="navbar-text navbar-right nav-item">
    <b>Your Cart:</b>
    @Model.Lines.Sum(x => x.Quantity) candies,
    @Model.ComputeTotalValue() RUB
</div>

CandyStore/UI/Views/NavCategory/Menu.cshtml
@model IEnumerable<string>

@foreach (var link in Model)
{
    @Html.RouteLink(link, new
    {
        controller = "Candy",
        action = "List",
        category = link,
        page = 1
    }, new
    {
        @class = "btn btn-block btn-default btn-lg rounded-pill border border-dark"
            + (link == ViewBag.SelectedCategory ? " btn-primary" : "")
    })
}

CandyStore/UI/Views/Shared/CandySummary.cshtml
@model Domain.Entities.Candy

<div class="card">

    <h3>
        @if (Model.ImageData != null)
        {
            <img class="img-thumbnail" align="left" width="100" height="100"
                 src="@Url.Action("GetImage", "Candy",
            new { Model.CandyId })" />
        }

        <strong style="margin-left:10px;">@Model.Name</strong>
        <span class="float-right badge badge-info">@Model.Price RUB</span>
        <span class="float-right badge badge-light">@Model.Weight Gr</span>

        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            <div>
                @Html.HiddenFor(x => x.CandyId)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" style="margin: 10px 0px 0px 10px" value="Add to the cart" />
            </div>
        }
    </h3>
    
    <span class="lead">@Model.Description</span>
</div>

CandyStore/UI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.0.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

CandyStore/UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-dark navbar-expand-sm bg-primary">
            <a class="navbar-brand" href="/">CandyStore - life sweeter with candies</a>
            @Html.Action("Summary", "Cart")
        </nav>
    </header>
    <main style="margin-top:20px;">
        <div class="row">
            <div id="categories" class="col-md-2" style="margin-left:10px;">
                @Html.Action("Menu", "NavCategory")
            </div>
            <div class="col-md-6 offset-1">
                @RenderBody()
            </div>
        </div>
    </main>
</body>
</html>